### ISSUE TITLE
[Question] SmartScreen and UAC

### ISSUE THREAD

**Issue by dennyamarojr** [CHEF-KOCH/Windows-10-hardening#36]
I have  see some hardening processes here in GitHub and find some guide that is saying that smartscreen doesn't protect the computer too much and also the  UAC. And some persons disable the UAC and also disable SmartScreen, could you tell me if is recommended this and also recommended disable Windows Security Center.

You recommend disable the services that this video shows ?
https://www.youtube.com/watch?v=iB0QvyN6v3E

Once again sorry for post in the wrong location, if is the right location  sorry for too many question, I'm noob in the hardening process.

**Comment by CHEF-KOCH** [comment]
This answer depends on your overall security strategy. Some believe in multilayered security protection, others don't. If you do not want/need the Windows own security mechanism and anti-virus solution and fully relay on external applications than there is not much of a point keeping these internal Windows services enabled because your third-party program will take over and do the entire job. Kaspersky for example will automatically disable Windows Defender (due to compatibility reason as well as performance reasons) once installed. It then integrates into the system center (or security center) and monitors events and notifies you.

If you believe in multilayered security you do not just relay on one feature/service to do the entire job because if that fails or does not detect everything you might expose yourself or make you vulnerable + unprotected.

I personally think that Windows Defender is incredible powerful and underrated. The GUI is sadly awful but there [exist tools to simplify the configuration process](https://github.com/AndyFul/Hard_Configurator). 

[SmartScreen](https://support.microsoft.com/en-us/help/17443/microsoft-edge-smartscreen-faq) is one component among others to fight malware on Windows, it detects unsigned files which makes it powerful, most people call this annoying because (sadly) some developers simply do not digital sign their applications which might results in a false/positive detection but it does already a good job, combined with Windows Defender and other Windows integrated protection mechanism. 

You also have to differ SC is not SC, you can enable system-wide SC or per-Browser SC. I assume you talk about Browser based SC AND the system-wide one (both typically enabled by default). You could fine-tune it, depends if you use MS Edge or another Browser and turn browser based SC off but let the system-wide SC on.

Important points:
- [UAC can be bypassed](https://github.com/hfiref0x/UACME)
- [SmartScreen](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview) also does not detect everything 
- Combining and settings everything to a higher-default standard already mitigates a lot of attacks against UAC/SC (not all).
- Combining SC/UAC (max) together with other Windows features is most effective.
- If you want another AV, consider to disable SC IF this AV already scans all HTTP(s) links/files on a real-time basis. Because "double" is not better and often results in a bad performance or even worse more false positive detections (which is one among many reasons why often third-party applications disabling Windows Defender).
- I suggest beginners NOT to disable SC or UAC, instead configure UAC (set it to max), configure SC (e.g. turn it off if you use another Browser which "does not support SC" or have their own safe-browsing filtering system in place like Firefox, Chrome, ...).

**Comment by dennyamarojr** [comment]
Thanks to clarify everything CHEF, will keep those services running.

**Comment by CHEF-KOCH** [comment]
I suggest using [H_C](https://github.com/AndyFul/Hard_Configurator) (set all settings to "recommend" and apply the settings). This alone defeats 99% of all malware. Nothing is 100% ever. But HC is more or less an easy tool to configure most important Windows build-in protection mechanism and quickly allows working with exceptions, black/-whitelists as well as easily change important settings (since as said, the WD/SecurityCenter GUI is awful).

And gives support in his [H_C thread](https://malwaretips.com/threads/hard_configurator-windows-hardening-configurator.66416/). He also explains a lot regarding Windows own security mechanism, how they work and how to defeat several problematic malware with pictures, examples etc. Worth reading the 142 pages if you're interested in Windows own protection mechanism and how to work with it.
